spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpacacha;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:file:~/jpacacha;DB_CLOSE_ON_EXIT=FALSE
#    ㄴ h2 콘솔에 db가 안날아가게 하고싶은경우
    username : sa
    password :
    driver-class-name: org.h2.Driver

  jpa :
    hibernate :
      ddl-auto: update
#      ddl-auto 를 create으로 하면 코드 돌릴때마다 h2 console이 초기화됨
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.hibernate.type : trace